---
name: Copies dockertag edge from ghcr

# from https://github.com/metcalfc/docker-action-examples/blob/main/app/Dockerfile
# When its time to do a release do a full cross platform build for all supported
# architectures and push all of them to Docker Hub.
on:
  push:
    tags:
      - "20[0-9]{5}"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # GitHub Actions do not automatically checkout your projects. If you need the code
      # you need to check it out.
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Prepare
      #   id: prep
      #   run: |
      #     G_EDGE_TAG=qs5779/python-multi:edge
      #     DOCKER_TAGS="${DOCKER_IMAGE}:${GITHUB_REF_NAME},${DOCKER_IMAGE}:latest"
      #     echo ::set-output name=dockertags::${DOCKER_TAGS}
      #     GHCR_IMAGE=gchcr.io/qs5779/python-multi
      #     GHCR_TAGS="${GHCR_IMAGE}:${GITHUB_REF_NAME},${GHCR_IMAGE}:latest"
          # echo ::set-output name=ghcrtags::${GHCR_TAGS}

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.WTF_ONE_FREE }}

      - name: Login to Github Container Repository
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - # run tests using image from docker hub
        name: Run Tests
        run: TAGS=ghcr.io/qs5779/python-multi:edge make test

      - # copy multiplatform image from dockerhub to quay and ghcr
        name: Push Image to multiple registries
        uses: akhilerm/tag-push-action@v2.0.0
        with:
          src: ghcr.io/qs5779/python-multi:edge
          dst: |
            ghcr.io/qs5779/python-multi:${GITHUB_REF_NAME}
            ghcr.io/qs5779/python-multi:latest
            qs5779/python-multi:${GITHUB_REF_NAME}
            qs5779/python-multi:latest
...
